### ISSUE TITLE
Translate Surveillance Self-Defense to Czech

### ISSUE THREAD

**Issue by honzakxt** [EFForg/www-l10n#24]
I would like to translate the SSD site to Czech. I have been told by EFF (Kim Carlson) to make a copy of the SSD site by downloading the files from https://github.com/EFForg/ssd, but it seems that there are only Drupal files and template files (css, fonts, images), but not the text content, which is probably stored in a database(?). We would like to have an SSD site replica up and running asap and start the translation. Do you think it would be possible to make a site DB dump public? (or at least the text content in some editable form (plain text, XLIFF, ...). Thank You.

**Comment by mfb** [comment]
The content is here in this repository, as XML file. However, I should prepare a new export for you, because the content in this repository is stale.

**Comment by honzakxt** [comment]
That would be great, thanks! BTW is it all I need to make a copy of the site? When I download https://github.com/EFForg/ssd, configure Apache, Drupal, DB and everything, how can I then import the text content from the XML file? I am not sure how to do that, I have no experience with Drupal...

**Comment by mfb** [comment]
Oops I thought this issue was opened on https://github.com/EFForg/ssd-l10n  🡐 this where the SSD content can be found.

**Comment by mfb** [comment]
As far as running your own version of the ssd.eff.org or obtaining a database thereof - no we do not support doing that. What you can do is write a script to parse the XML file and inject the content into a site of your choice, whether a Drupal site or anything else.

**Comment by honzakxt** [comment]
Thank you Mark, can I have one more question?
Which file on https://github.com/EFForg/ssd-l10n should I get? There are several localizations... Or is it that each of them contains also the english original?
EDIT: OK, I read something about the file format and there is a source in each of them, so it should be OK to take any of them. I will just wait for a fresh export.

Thank You!

**Comment by mfb** [comment]
The most up-to-date content is here: https://github.com/EFForg/ssd-l10n/tree/master/translations/es

**Comment by honzakxt** [comment]
Great, thanks!
