### ISSUE TITLE
how can i push a translation?

### ISSUE THREAD

**Issue by obazia** [EFForg/www-l10n#3]
Hi.
After downloading the repository with git checkout, I've translated some FAQs of the  XLIFF file into Italian, but apparently I'm not allowed to push my translation to the repo again. I wonder if I have to create a branch and then request a merge or do something else. Can anybody give me details?

Thanks :)
obaz

this is what happens after i try "git push origin master":

ERROR: Permission to EFForg/www-l10n.git denied to obazia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mfb** [comment]
Thanks for contributing :)  You can fork the repository, create a branch for your work, commit, push to your own repo and then submit a pull request. See also https://help.github.com/
